#ifndef REQUESTS_H
#define REQUESTS_H

// Listado de constantes de solicitudes
#define INSERTAR_FIGURITA "INSERTAR_FIGURITA"
#define VER_FIGURITAS "VER_FIGURITAS"

#define INSERTAR_USUARIO "INSERTAR_USUARIO"
#define BAJA_USUARIO "BAJA_USUARIO"
#define VER_USUARIOS_ACTIVOS "VER_USUARIOS_ACTIVOS"

#define INSERTAR_PETICION_INTERCAMBIO "INSERTAR_PETICION_INTERCAMBIO"

#endif // REQUESTS_H