#ifndef REQUESTS_H
#define REQUESTS_H

// Listado de constantes de solicitudes
#define INSERTAR_FIGURITA "INSERTAR_FIGURITA"
#define VER_FIGURITAS "VER_FIGURITAS"

#define INSERTAR_USUARIO "INSERTAR_USUARIO"
#define BAJA_USUARIO "BAJA_USUARIO"
#define VER_USUARIOS_ACTIVOS "VER_USUARIOS_ACTIVOS"

#define INSERTAR_PETICION_INTERCAMBIO "INSERTAR_PETICION_INTERCAMBIO"
#define CANCELAR_PETICION_INTERCAMBIO "CANCELAR_PETICION_INTERCAMBIO"

#define VER_REGISTRO_ACTIVIDADES "VER_REGISTRO_ACTIVIDADES"

#define SOLICITAR_ROL "SOLICITAR_ROL"

#define FIN "FIN"
#define OK "OK"
#endif // REQUESTS_H